name: First test action
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm install
            - name: Test app
              run: npm run test
            - name: Upload artifacts
              uses: actions/upload-artifacts@v3
              with:
                  name: build-files
                  path: build
    build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: build-files
            - name: Build app
              run: npm run build
