name: Learning

on:
    push:
        branches:
            - master

jobs:
    checking:
        runs-on: ubuntu:latest
        steps:
            - name: 'Who am I?'
              run: whoami

            - name: 'Where am I'
              run: pwd
