name: CI/CD with Docker Hub

on:
    push:
        branches:
            - master

env:
    REGISTRY: 'docker.io'
    IMAGE_NAME: 'rasif1996/react'

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Build container image
              run: docker build -t "$(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)" .

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Remove all old images
              run: docker rmi "$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)" || true

            - name: Push image to Docker Hub
              run: docker push "$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)"

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build_and_push
    #     steps:
    #         - name: Deploy to Digital Ocean droplet via SSH action
    #           uses: appleboy/ssh-action@v0.1.3
    #           with:
    #               host: ${{ secrets.SSH_HOST }}
    #               port: ${{secrets.SSH_PORT}}
    #               username: ${{ secrets.SSH_USERNAME }}
    #               key: ${{ secrets.SSH_KEY }}
    #               envs: IMAGE_NAME,GITHUB_SHA
    #               script: |
    #                   docker stop $(echo $IMAGE_NAME)
    #                   docker rm $(echo $IMAGE_NAME)
    #                   docker pull $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
    #                   docker run -d \
    #                   --restart always \
    #                   --name $(echo $IMAGE_NAME) \
    #                   $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
