name: CI/CD with Docker Hub

on:
    push:
        branches:
            - master

env:
    REGISTRY: 'docker.io'
    IMAGE_NAME: 'rasif1996/react'
    PORT: 3000
jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Build container image
              run: docker build --build-arg PORT=$(echo $PORT) -t "$(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)" .

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Push image to Docker Hub
              run: docker push "$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)"

    deploy:
        runs-on: ubuntu-latest
        needs: build_and_push
        steps:
            - name: Deploy to Digital Ocean droplet via SSH action
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{secrets.SSH_PORT}}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  envs: IMAGE_NAME,GITHUB_SHA
                  script: |
                      docker stop $(echo $IMAGE_NAME)
                      docker rm $(echo $IMAGE_NAME)
                      docker pull $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
                      docker run -d \
                      --restart always \
                      --name container \
                      -p 80:$(echo $PORT) \
                      $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
